"""empty message

Revision ID: 1b5f203f21a5
Revises: 457cc92e7307
Create Date: 2016-04-29 17:02:37.935515

"""

# ignore flake8 checks as files generated by Alembic are not PEP8 compatible
# flake8: noqa

# revision identifiers, used by Alembic.
revision = '1b5f203f21a5'
down_revision = '457cc92e7307'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_toadd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('advisor', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('imageUrl', sa.String(length=50), nullable=True),
    sa.Column('currentOrganisation', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('program', sa.String(length=50), nullable=True),
    sa.Column('webAddress', sa.String(length=50), nullable=True),
    sa.Column('graduationyear', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'alumni', sa.Column('advisor', sa.String(length=50), nullable=True))
    op.add_column(u'alumni', sa.Column('currentOrganisation', sa.String(length=50), nullable=True))
    op.add_column(u'alumni', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column(u'alumni', sa.Column('imageUrl', sa.String(length=50), nullable=True))
    op.add_column(u'alumni', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column(u'alumni', sa.Column('program', sa.String(length=50), nullable=True))
    op.add_column(u'alumni', sa.Column('webAddress', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'alumni', 'webAddress')
    op.drop_column(u'alumni', 'program')
    op.drop_column(u'alumni', 'phone')
    op.drop_column(u'alumni', 'imageUrl')
    op.drop_column(u'alumni', 'email')
    op.drop_column(u'alumni', 'currentOrganisation')
    op.drop_column(u'alumni', 'advisor')
    op.drop_table('alumni_toadd')
    ### end Alembic commands ###
