"""empty message

Revision ID: 2c4abc4a518c
Revises: 314d2c19fc9
Create Date: 2016-03-29 03:28:31.345951

"""

# ignore flake8 checks as files generated by Alembic are not PEP8 compatible
# flake8: noqa

# revision identifiers, used by Alembic.
revision = '2c4abc4a518c'
down_revision = '314d2c19fc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
