"""empty message

Revision ID: 314d2c19fc9
Revises: None
Create Date: 2016-03-29 03:20:31.658067

"""

# ignore flake8 checks as files generated by Alembic are not PEP8 compatible
# flake8: noqa

# revision identifiers, used by Alembic.
revision = '314d2c19fc9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('numberavailable', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    ### end Alembic commands ###
