"""empty message

Revision ID: 36f0758013b4
Revises: 2c4abc4a518c
Create Date: 2016-03-29 03:38:26.091642

"""

# ignore flake8 checks as files generated by Alembic are not PEP8 compatible
# flake8: noqa

# revision identifiers, used by Alembic.
revision = '36f0758013b4'
down_revision = '2c4abc4a518c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
