"""empty message

Revision ID: 3705225d7771
Revises: 1b5f203f21a5
Create Date: 2016-04-29 17:48:59.489821

"""

# ignore flake8 checks as files generated by Alembic are not PEP8 compatible
# flake8: noqa

# revision identifiers, used by Alembic.
revision = '3705225d7771'
down_revision = '1b5f203f21a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
